; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:gscesp]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
build_src_filter = -<*> +<gscesp/*>
lib_deps = adafruit/Adafruit ADS1X15@^2.6.2

[env:teensy]
platform = teensy
board = teensy41
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit BusIO@^1.16.1
	adafruit/Adafruit ADS1X15@^2.6.2
upload_port = COM8
monitor_port = COM8
build_src_filter = -<*> +<teensy/*>

[env:tsesp]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
build_src_filter = -<*> +<tsesp/*>
lib_deps = adafruit/Adafruit ADS1X15@^2.6.2
