import csv
import argparse
import struct
from pathlib import Path

# -----------------------------
# CONFIG
# -----------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
INPUT_FILE = SCRIPT_DIR / "data.bin"
OUTPUT_DIR = SCRIPT_DIR / "decoded"

MARKER = 0xA5A5A5A5
MARKER_BYTES = struct.pack("<I", MARKER)
MAX_SENSOR_COUNT = 64

# Frame layout (dynamic by sensor_count):
# uint32_t timestamp_us
# uint32_t seq
# uint8_t  valid_mask
# uint8_t  status_bits
# uint16_t sol_state
# uint32_t payload[sensor_count]
# uint16_t raw_adc[sensor_count]

# Session header:
# uint32_t marker
# uint16_t sensor_count
HEADER_FMT = "<I H"
HEADER_SIZE = struct.calcsize(HEADER_FMT)


# -----------------------------
# Helpers
# -----------------------------
def find_all_markers(data: bytes):
    offsets = []
    start = 0

    while True:
        idx = data.find(MARKER_BYTES, start)

        if idx == -1:
            break

        offsets.append(idx)
        start = idx + 4

    return offsets


def build_frame_format(sensor_count: int):
    if sensor_count < 1 or sensor_count > MAX_SENSOR_COUNT:
        raise ValueError(f"sensor_count out of range: {sensor_count}")

    fmt = f"<I I B B H {sensor_count}I {sensor_count}H"
    size = struct.calcsize(fmt)
    return fmt, size


def decode_frames(region: bytes, sensor_count: int):
    frames = []
    frame_fmt, frame_size = build_frame_format(sensor_count)

    usable_len = len(region) - (len(region) % frame_size)

    for off in range(0, usable_len, frame_size):
        chunk = region[off:off + frame_size]

        try:
            vals = struct.unpack(frame_fmt, chunk)
        except struct.error:
            break

        ts_us = vals[0]
        seq = vals[1]
        valid_mask = vals[2]
        status_bits = vals[3]
        sol_state = vals[4]

        payload_all = list(vals[5:5 + sensor_count])
        adc_all = list(vals[5 + sensor_count:5 + sensor_count + sensor_count])

        frame = {
            "timestamp_us": ts_us,
            "seq": seq,
            "valid_mask": valid_mask,
            "status_bits": status_bits,
            "solenoid_state": sol_state,
        }

        for i in range(sensor_count):
            frame[f"payload{i}_centi_psi"] = payload_all[i]
            frame[f"raw_adc{i}"] = adc_all[i]

        frames.append(frame)

    return frames


def write_csv(frames, path: Path, sensor_count: int):
    path.parent.mkdir(parents=True, exist_ok=True)

    headers = [
        "timestamp_us",
        "seq",
        "valid_mask",
        "status_bits",
        "solenoid_state",
    ]

    for i in range(sensor_count):
        headers.append(f"payload{i}_centi_psi")

    for i in range(sensor_count):
        headers.append(f"raw_adc{i}")

    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(frames)


def estimate_rate(frames):
    if len(frames) < 2:
        return None

    deltas = []

    for i in range(1, len(frames)):
        dt = (
            frames[i]["timestamp_us"]
            - frames[i - 1]["timestamp_us"]
        ) & 0xFFFFFFFF

        if 0 < dt < 5_000_000:
            deltas.append(dt)

    if not deltas:
        return None

    avg_dt = sum(deltas) / len(deltas)

    return 1_000_000.0 / avg_dt


# -----------------------------
# Main
# -----------------------------
def main():
    parser = argparse.ArgumentParser(
        description=(
            "Decode SD .bin logs generated by firmware sessions with "
            "[marker:uint32][sensor_count:uint16] headers."
        )
    )
    parser.add_argument(
        "input_file",
        nargs="?",
        default=str(INPUT_FILE),
        help="Path to input .bin file (default: data.bin)",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        default=str(OUTPUT_DIR),
        help="Directory for decoded session CSVs (default: decoded)",
    )
    args = parser.parse_args()

    input_file = Path(args.input_file)
    output_dir = Path(args.output_dir)

    if not input_file.exists():
        print(f"ERROR: Input file not found: {input_file}")
        return

    data = input_file.read_bytes()

    markers = find_all_markers(data)

    if not markers:
        print("ERROR: No session marker found.")
        return

    print(f"Found {len(markers)} possible session marker(s).")

    valid_sessions = 0

    for i, marker_pos in enumerate(markers):

        # Ensure full header exists
        if marker_pos + HEADER_SIZE > len(data):
            continue

        try:
            marker, sensor_count = struct.unpack_from(
                HEADER_FMT,
                data,
                marker_pos
            )
        except struct.error:
            continue

        # Reject false-positive markers
        if marker != MARKER:
            continue

        if sensor_count < 1 or sensor_count > MAX_SENSOR_COUNT:
            print(
                f"Skipping false marker at offset {marker_pos} "
                f"(sensor_count={sensor_count})"
            )
            continue

        start = marker_pos + HEADER_SIZE

        # Find next VALID marker
        end = len(data)

        for next_pos in markers:
            if next_pos <= marker_pos:
                continue

            if next_pos + HEADER_SIZE > len(data):
                continue

            try:
                next_marker, next_sensor_count = struct.unpack_from(
                    HEADER_FMT,
                    data,
                    next_pos
                )
            except struct.error:
                continue

            if (
                next_marker == MARKER and
                1 <= next_sensor_count <= MAX_SENSOR_COUNT
            ):
                end = next_pos
                break

        region = data[start:end]

        frames = decode_frames(region, sensor_count)

        output_file = output_dir / f"session_{valid_sessions:03d}.csv"

        write_csv(frames, output_file, sensor_count)

        rate = estimate_rate(frames)
        rate_str = f"{rate:.2f} Hz" if rate else "unknown"

        print(
            f"Session {valid_sessions:03d}: "
            f"{len(frames)} frames | "
            f"{sensor_count} sensors | "
            f"Estimated rate: {rate_str} | "
            f"{output_file}"
        )

        valid_sessions += 1

    print(f"\nDone. Wrote {valid_sessions} session file(s) to: {output_dir}")


if __name__ == "__main__":
    main()
